// const characters3 = ['3-D Man', 'A-Bomb (HAS)', 'A.I.M.', 'Aaron Stack'];

const characters = [
  { id: 1, 
    name: '3-D Man', 
    description: 'v1', 
    imageURL: 'http://i.imgflip.com/1bij.jpg', 
    profileURL: 'http://i.imgflip.com/1bij.jpg', 
    comicsURL: 'http://i.imgflip.com/1bij.jpg', 
    comicsCount: 1,
    storiesCount: 1,
  },
  { id: 2, 
    name: 'A-Bomb (HAS)',
    description: 'v2', 
    imageURL: 'http://i.imgflip.com/1bij.jpg', 
    profileURL: 'http://i.imgflip.com/1bij.jpg', 
    comicsURL: 'http://i.imgflip.com/1bij.jpg', 
    comicsCount: 2,
    storiesCount: 2,
  }, 
  { id: 3, 
    name: 'A.I.M.',        
    description: 'v3', 
    imageURL: 'http://i.imgflip.com/1bij.jpg', 
    profileURL: 'http://i.imgflip.com/1bij.jpg', 
    comicsURL: 'http://i.imgflip.com/1bij.jpg', 
    comicsCount: 3,
    storiesCount: 3,
  },
  { id: 4, 
    name: 'Aaron Stack',
    description: 'v1', 
    imageURL: 'http://i.imgflip.com/1bij.jpg', 
    profileURL: 'http://i.imgflip.com/1bij.jpg', 
    comicsURL: 'http://i.imgflip.com/1bij.jpg', 
    comicsCount: 4,
    storiesCount: 4,
  },
];

export default characters;